//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.08 at 05:59:48 PM PDT 
//


package net.authorize.apicore.contract.v1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ARBGetSubscriptionListSearchTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ARBGetSubscriptionListSearchTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CardExpiringThisMonth"/>
 *     &lt;enumeration value="SubscriptionActive"/>
 *     &lt;enumeration value="SubscriptionExpiringThisMonth"/>
 *     &lt;enumeration value="SubscriptionInactive"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ARBGetSubscriptionListSearchTypeEnum")
@XmlEnum
public enum ARBGetSubscriptionListSearchTypeEnum {

    @XmlEnumValue("CardExpiringThisMonth")
    CARD_EXPIRING_THIS_MONTH("CardExpiringThisMonth"),
    @XmlEnumValue("SubscriptionActive")
    SUBSCRIPTION_ACTIVE("SubscriptionActive"),
    @XmlEnumValue("SubscriptionExpiringThisMonth")
    SUBSCRIPTION_EXPIRING_THIS_MONTH("SubscriptionExpiringThisMonth"),
    @XmlEnumValue("SubscriptionInactive")
    SUBSCRIPTION_INACTIVE("SubscriptionInactive");
    private final String value;

    ARBGetSubscriptionListSearchTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ARBGetSubscriptionListSearchTypeEnum fromValue(String v) {
        for (ARBGetSubscriptionListSearchTypeEnum c: ARBGetSubscriptionListSearchTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
