//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.06 at 01:39:26 PM PDT 
//


package net.authorize.apicore.contract.v1;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.authorize.apicore.contract.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ErrorResponse_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "ErrorResponse");
    private final static QName _TransactionDetailsTypeOrder_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "order");
    private final static QName _TransactionDetailsTypeRefTransId_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "refTransId");
    private final static QName _TransactionDetailsTypePayment_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "payment");
    private final static QName _TransactionDetailsTypeCardCodeResponse_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "cardCodeResponse");
    private final static QName _TransactionDetailsTypeBillTo_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "billTo");
    private final static QName _TransactionDetailsTypeShipping_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "shipping");
    private final static QName _TransactionDetailsTypeMobileDeviceId_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "mobileDeviceId");
    private final static QName _TransactionDetailsTypeLineItems_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "lineItems");
    private final static QName _TransactionDetailsTypeResponseCode_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "responseCode");
    private final static QName _TransactionDetailsTypeMarketType_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "marketType");
    private final static QName _TransactionDetailsTypeSubscription_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "subscription");
    private final static QName _TransactionDetailsTypeResponseReasonDescription_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "responseReasonDescription");
    private final static QName _TransactionDetailsTypeSubmitTimeLocal_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "submitTimeLocal");
    private final static QName _TransactionDetailsTypeSettleAmount_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "settleAmount");
    private final static QName _TransactionDetailsTypeTransId_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "transId");
    private final static QName _TransactionDetailsTypeSplitTenderId_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "splitTenderId");
    private final static QName _TransactionDetailsTypeCustomerIP_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "customerIP");
    private final static QName _TransactionDetailsTypeSubmitTimeUTC_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "submitTimeUTC");
    private final static QName _TransactionDetailsTypeCustomer_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "customer");
    private final static QName _TransactionDetailsTypeShipTo_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "shipTo");
    private final static QName _TransactionDetailsTypeRequestedAmount_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "requestedAmount");
    private final static QName _TransactionDetailsTypeDuty_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "duty");
    private final static QName _TransactionDetailsTypeCAVVResponse_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "CAVVResponse");
    private final static QName _TransactionDetailsTypeRecurringBilling_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "recurringBilling");
    private final static QName _TransactionDetailsTypeTransactionType_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "transactionType");
    private final static QName _TransactionDetailsTypeFDSFilterAction_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "FDSFilterAction");
    private final static QName _TransactionDetailsTypeResponseReasonCode_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "responseReasonCode");
    private final static QName _TransactionDetailsTypePrepaidBalanceRemaining_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "prepaidBalanceRemaining");
    private final static QName _TransactionDetailsTypeFDSFilters_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "FDSFilters");
    private final static QName _TransactionDetailsTypeAuthAmount_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "authAmount");
    private final static QName _TransactionDetailsTypeTax_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "tax");
    private final static QName _TransactionDetailsTypeBatch_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "batch");
    private final static QName _TransactionDetailsTypeTransactionStatus_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "transactionStatus");
    private final static QName _TransactionDetailsTypeAuthCode_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "authCode");
    private final static QName _TransactionDetailsTypeTaxExempt_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "taxExempt");
    private final static QName _TransactionDetailsTypeProduct_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "product");
    private final static QName _TransactionDetailsTypeAVSResponse_QNAME = new QName("AnetApi/xml/v1/schema/AnetApiSchema.xsd", "AVSResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.authorize.apicore.contract.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KeyManagementScheme }
     * 
     */
    public KeyManagementScheme createKeyManagementScheme() {
        return new KeyManagementScheme();
    }

    /**
     * Create an instance of {@link KeyManagementScheme.DUKPT }
     * 
     */
    public KeyManagementScheme.DUKPT createKeyManagementSchemeDUKPT() {
        return new KeyManagementScheme.DUKPT();
    }

    /**
     * Create an instance of {@link PaymentScheduleType }
     * 
     */
    public PaymentScheduleType createPaymentScheduleType() {
        return new PaymentScheduleType();
    }

    /**
     * Create an instance of {@link TransactionRequestType }
     * 
     */
    public TransactionRequestType createTransactionRequestType() {
        return new TransactionRequestType();
    }

    /**
     * Create an instance of {@link TransactionResponse }
     * 
     */
    public TransactionResponse createTransactionResponse() {
        return new TransactionResponse();
    }

    /**
     * Create an instance of {@link TransactionResponse.SplitTenderPayments }
     * 
     */
    public TransactionResponse.SplitTenderPayments createTransactionResponseSplitTenderPayments() {
        return new TransactionResponse.SplitTenderPayments();
    }

    /**
     * Create an instance of {@link TransactionResponse.Errors }
     * 
     */
    public TransactionResponse.Errors createTransactionResponseErrors() {
        return new TransactionResponse.Errors();
    }

    /**
     * Create an instance of {@link TransactionResponse.Messages }
     * 
     */
    public TransactionResponse.Messages createTransactionResponseMessages() {
        return new TransactionResponse.Messages();
    }

    /**
     * Create an instance of {@link MessagesType }
     * 
     */
    public MessagesType createMessagesType() {
        return new MessagesType();
    }

    /**
     * Create an instance of {@link GetCustomerProfileResponse }
     * 
     */
    public GetCustomerProfileResponse createGetCustomerProfileResponse() {
        return new GetCustomerProfileResponse();
    }

    /**
     * Create an instance of {@link ANetApiResponse }
     * 
     */
    public ANetApiResponse createANetApiResponse() {
        return new ANetApiResponse();
    }

    /**
     * Create an instance of {@link CustomerProfileMaskedType }
     * 
     */
    public CustomerProfileMaskedType createCustomerProfileMaskedType() {
        return new CustomerProfileMaskedType();
    }

    /**
     * Create an instance of {@link MobileDeviceRegistrationResponse }
     * 
     */
    public MobileDeviceRegistrationResponse createMobileDeviceRegistrationResponse() {
        return new MobileDeviceRegistrationResponse();
    }

    /**
     * Create an instance of {@link CreateCustomerProfileResponse }
     * 
     */
    public CreateCustomerProfileResponse createCreateCustomerProfileResponse() {
        return new CreateCustomerProfileResponse();
    }

    /**
     * Create an instance of {@link ArrayOfNumericString }
     * 
     */
    public ArrayOfNumericString createArrayOfNumericString() {
        return new ArrayOfNumericString();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link UpdateCustomerProfileRequest }
     * 
     */
    public UpdateCustomerProfileRequest createUpdateCustomerProfileRequest() {
        return new UpdateCustomerProfileRequest();
    }

    /**
     * Create an instance of {@link ANetApiRequest }
     * 
     */
    public ANetApiRequest createANetApiRequest() {
        return new ANetApiRequest();
    }

    /**
     * Create an instance of {@link MerchantAuthenticationType }
     * 
     */
    public MerchantAuthenticationType createMerchantAuthenticationType() {
        return new MerchantAuthenticationType();
    }

    /**
     * Create an instance of {@link CustomerProfileExType }
     * 
     */
    public CustomerProfileExType createCustomerProfileExType() {
        return new CustomerProfileExType();
    }

    /**
     * Create an instance of {@link DeleteCustomerShippingAddressRequest }
     * 
     */
    public DeleteCustomerShippingAddressRequest createDeleteCustomerShippingAddressRequest() {
        return new DeleteCustomerShippingAddressRequest();
    }

    /**
     * Create an instance of {@link DeleteCustomerShippingAddressResponse }
     * 
     */
    public DeleteCustomerShippingAddressResponse createDeleteCustomerShippingAddressResponse() {
        return new DeleteCustomerShippingAddressResponse();
    }

    /**
     * Create an instance of {@link ARBCancelSubscriptionRequest }
     * 
     */
    public ARBCancelSubscriptionRequest createARBCancelSubscriptionRequest() {
        return new ARBCancelSubscriptionRequest();
    }

    /**
     * Create an instance of {@link ValidateCustomerPaymentProfileRequest }
     * 
     */
    public ValidateCustomerPaymentProfileRequest createValidateCustomerPaymentProfileRequest() {
        return new ValidateCustomerPaymentProfileRequest();
    }

    /**
     * Create an instance of {@link UpdateCustomerShippingAddressRequest }
     * 
     */
    public UpdateCustomerShippingAddressRequest createUpdateCustomerShippingAddressRequest() {
        return new UpdateCustomerShippingAddressRequest();
    }

    /**
     * Create an instance of {@link CustomerAddressExType }
     * 
     */
    public CustomerAddressExType createCustomerAddressExType() {
        return new CustomerAddressExType();
    }

    /**
     * Create an instance of {@link GetSettledBatchListResponse }
     * 
     */
    public GetSettledBatchListResponse createGetSettledBatchListResponse() {
        return new GetSettledBatchListResponse();
    }

    /**
     * Create an instance of {@link ArrayOfBatchDetailsType }
     * 
     */
    public ArrayOfBatchDetailsType createArrayOfBatchDetailsType() {
        return new ArrayOfBatchDetailsType();
    }

    /**
     * Create an instance of {@link GetCustomerShippingAddressRequest }
     * 
     */
    public GetCustomerShippingAddressRequest createGetCustomerShippingAddressRequest() {
        return new GetCustomerShippingAddressRequest();
    }

    /**
     * Create an instance of {@link CreateCustomerShippingAddressResponse }
     * 
     */
    public CreateCustomerShippingAddressResponse createCreateCustomerShippingAddressResponse() {
        return new CreateCustomerShippingAddressResponse();
    }

    /**
     * Create an instance of {@link GetCustomerShippingAddressResponse }
     * 
     */
    public GetCustomerShippingAddressResponse createGetCustomerShippingAddressResponse() {
        return new GetCustomerShippingAddressResponse();
    }

    /**
     * Create an instance of {@link UpdateCustomerProfileResponse }
     * 
     */
    public UpdateCustomerProfileResponse createUpdateCustomerProfileResponse() {
        return new UpdateCustomerProfileResponse();
    }

    /**
     * Create an instance of {@link DeleteCustomerProfileResponse }
     * 
     */
    public DeleteCustomerProfileResponse createDeleteCustomerProfileResponse() {
        return new DeleteCustomerProfileResponse();
    }

    /**
     * Create an instance of {@link GetUnsettledTransactionListRequest }
     * 
     */
    public GetUnsettledTransactionListRequest createGetUnsettledTransactionListRequest() {
        return new GetUnsettledTransactionListRequest();
    }

    /**
     * Create an instance of {@link LogoutRequest }
     * 
     */
    public LogoutRequest createLogoutRequest() {
        return new LogoutRequest();
    }

    /**
     * Create an instance of {@link SendCustomerTransactionReceiptRequest }
     * 
     */
    public SendCustomerTransactionReceiptRequest createSendCustomerTransactionReceiptRequest() {
        return new SendCustomerTransactionReceiptRequest();
    }

    /**
     * Create an instance of {@link EmailSettingsType }
     * 
     */
    public EmailSettingsType createEmailSettingsType() {
        return new EmailSettingsType();
    }

    /**
     * Create an instance of {@link UpdateSplitTenderGroupRequest }
     * 
     */
    public UpdateSplitTenderGroupRequest createUpdateSplitTenderGroupRequest() {
        return new UpdateSplitTenderGroupRequest();
    }

    /**
     * Create an instance of {@link ARBGetSubscriptionStatusResponse }
     * 
     */
    public ARBGetSubscriptionStatusResponse createARBGetSubscriptionStatusResponse() {
        return new ARBGetSubscriptionStatusResponse();
    }

    /**
     * Create an instance of {@link IsAliveResponse }
     * 
     */
    public IsAliveResponse createIsAliveResponse() {
        return new IsAliveResponse();
    }

    /**
     * Create an instance of {@link CreateCustomerShippingAddressRequest }
     * 
     */
    public CreateCustomerShippingAddressRequest createCreateCustomerShippingAddressRequest() {
        return new CreateCustomerShippingAddressRequest();
    }

    /**
     * Create an instance of {@link CustomerAddressType }
     * 
     */
    public CustomerAddressType createCustomerAddressType() {
        return new CustomerAddressType();
    }

    /**
     * Create an instance of {@link ARBUpdateSubscriptionResponse }
     * 
     */
    public ARBUpdateSubscriptionResponse createARBUpdateSubscriptionResponse() {
        return new ARBUpdateSubscriptionResponse();
    }

    /**
     * Create an instance of {@link CreateCustomerProfileTransactionResponse }
     * 
     */
    public CreateCustomerProfileTransactionResponse createCreateCustomerProfileTransactionResponse() {
        return new CreateCustomerProfileTransactionResponse();
    }

    /**
     * Create an instance of {@link CreateTransactionResponse }
     * 
     */
    public CreateTransactionResponse createCreateTransactionResponse() {
        return new CreateTransactionResponse();
    }

    /**
     * Create an instance of {@link GetTransactionDetailsRequest }
     * 
     */
    public GetTransactionDetailsRequest createGetTransactionDetailsRequest() {
        return new GetTransactionDetailsRequest();
    }

    /**
     * Create an instance of {@link GetBatchStatisticsResponse }
     * 
     */
    public GetBatchStatisticsResponse createGetBatchStatisticsResponse() {
        return new GetBatchStatisticsResponse();
    }

    /**
     * Create an instance of {@link BatchDetailsType }
     * 
     */
    public BatchDetailsType createBatchDetailsType() {
        return new BatchDetailsType();
    }

    /**
     * Create an instance of {@link GetSettledBatchListRequest }
     * 
     */
    public GetSettledBatchListRequest createGetSettledBatchListRequest() {
        return new GetSettledBatchListRequest();
    }

    /**
     * Create an instance of {@link UpdateSplitTenderGroupResponse }
     * 
     */
    public UpdateSplitTenderGroupResponse createUpdateSplitTenderGroupResponse() {
        return new UpdateSplitTenderGroupResponse();
    }

    /**
     * Create an instance of {@link IsAliveRequest }
     * 
     */
    public IsAliveRequest createIsAliveRequest() {
        return new IsAliveRequest();
    }

    /**
     * Create an instance of {@link CreateCustomerPaymentProfileResponse }
     * 
     */
    public CreateCustomerPaymentProfileResponse createCreateCustomerPaymentProfileResponse() {
        return new CreateCustomerPaymentProfileResponse();
    }

    /**
     * Create an instance of {@link GetCustomerPaymentProfileRequest }
     * 
     */
    public GetCustomerPaymentProfileRequest createGetCustomerPaymentProfileRequest() {
        return new GetCustomerPaymentProfileRequest();
    }

    /**
     * Create an instance of {@link GetCustomerPaymentProfileResponse }
     * 
     */
    public GetCustomerPaymentProfileResponse createGetCustomerPaymentProfileResponse() {
        return new GetCustomerPaymentProfileResponse();
    }

    /**
     * Create an instance of {@link CustomerPaymentProfileMaskedType }
     * 
     */
    public CustomerPaymentProfileMaskedType createCustomerPaymentProfileMaskedType() {
        return new CustomerPaymentProfileMaskedType();
    }

    /**
     * Create an instance of {@link LogoutResponse }
     * 
     */
    public LogoutResponse createLogoutResponse() {
        return new LogoutResponse();
    }

    /**
     * Create an instance of {@link MobileDeviceLoginRequest }
     * 
     */
    public MobileDeviceLoginRequest createMobileDeviceLoginRequest() {
        return new MobileDeviceLoginRequest();
    }

    /**
     * Create an instance of {@link GetTransactionDetailsResponse }
     * 
     */
    public GetTransactionDetailsResponse createGetTransactionDetailsResponse() {
        return new GetTransactionDetailsResponse();
    }

    /**
     * Create an instance of {@link TransactionDetailsType }
     * 
     */
    public TransactionDetailsType createTransactionDetailsType() {
        return new TransactionDetailsType();
    }

    /**
     * Create an instance of {@link ARBUpdateSubscriptionRequest }
     * 
     */
    public ARBUpdateSubscriptionRequest createARBUpdateSubscriptionRequest() {
        return new ARBUpdateSubscriptionRequest();
    }

    /**
     * Create an instance of {@link ARBSubscriptionType }
     * 
     */
    public ARBSubscriptionType createARBSubscriptionType() {
        return new ARBSubscriptionType();
    }

    /**
     * Create an instance of {@link GetCustomerProfileIdsRequest }
     * 
     */
    public GetCustomerProfileIdsRequest createGetCustomerProfileIdsRequest() {
        return new GetCustomerProfileIdsRequest();
    }

    /**
     * Create an instance of {@link GetCustomerProfileRequest }
     * 
     */
    public GetCustomerProfileRequest createGetCustomerProfileRequest() {
        return new GetCustomerProfileRequest();
    }

    /**
     * Create an instance of {@link ARBCreateSubscriptionResponse }
     * 
     */
    public ARBCreateSubscriptionResponse createARBCreateSubscriptionResponse() {
        return new ARBCreateSubscriptionResponse();
    }

    /**
     * Create an instance of {@link AuthenticateTestResponse }
     * 
     */
    public AuthenticateTestResponse createAuthenticateTestResponse() {
        return new AuthenticateTestResponse();
    }

    /**
     * Create an instance of {@link CreateCustomerProfileRequest }
     * 
     */
    public CreateCustomerProfileRequest createCreateCustomerProfileRequest() {
        return new CreateCustomerProfileRequest();
    }

    /**
     * Create an instance of {@link CustomerProfileType }
     * 
     */
    public CustomerProfileType createCustomerProfileType() {
        return new CustomerProfileType();
    }

    /**
     * Create an instance of {@link ARBCancelSubscriptionResponse }
     * 
     */
    public ARBCancelSubscriptionResponse createARBCancelSubscriptionResponse() {
        return new ARBCancelSubscriptionResponse();
    }

    /**
     * Create an instance of {@link ARBGetSubscriptionStatusRequest }
     * 
     */
    public ARBGetSubscriptionStatusRequest createARBGetSubscriptionStatusRequest() {
        return new ARBGetSubscriptionStatusRequest();
    }

    /**
     * Create an instance of {@link DeleteCustomerPaymentProfileRequest }
     * 
     */
    public DeleteCustomerPaymentProfileRequest createDeleteCustomerPaymentProfileRequest() {
        return new DeleteCustomerPaymentProfileRequest();
    }

    /**
     * Create an instance of {@link UpdateCustomerPaymentProfileResponse }
     * 
     */
    public UpdateCustomerPaymentProfileResponse createUpdateCustomerPaymentProfileResponse() {
        return new UpdateCustomerPaymentProfileResponse();
    }

    /**
     * Create an instance of {@link DeleteCustomerProfileRequest }
     * 
     */
    public DeleteCustomerProfileRequest createDeleteCustomerProfileRequest() {
        return new DeleteCustomerProfileRequest();
    }

    /**
     * Create an instance of {@link CreateTransactionRequest }
     * 
     */
    public CreateTransactionRequest createCreateTransactionRequest() {
        return new CreateTransactionRequest();
    }

    /**
     * Create an instance of {@link DeleteCustomerPaymentProfileResponse }
     * 
     */
    public DeleteCustomerPaymentProfileResponse createDeleteCustomerPaymentProfileResponse() {
        return new DeleteCustomerPaymentProfileResponse();
    }

    /**
     * Create an instance of {@link CreateCustomerProfileTransactionRequest }
     * 
     */
    public CreateCustomerProfileTransactionRequest createCreateCustomerProfileTransactionRequest() {
        return new CreateCustomerProfileTransactionRequest();
    }

    /**
     * Create an instance of {@link ProfileTransactionType }
     * 
     */
    public ProfileTransactionType createProfileTransactionType() {
        return new ProfileTransactionType();
    }

    /**
     * Create an instance of {@link MobileDeviceLoginResponse }
     * 
     */
    public MobileDeviceLoginResponse createMobileDeviceLoginResponse() {
        return new MobileDeviceLoginResponse();
    }

    /**
     * Create an instance of {@link MerchantContactType }
     * 
     */
    public MerchantContactType createMerchantContactType() {
        return new MerchantContactType();
    }

    /**
     * Create an instance of {@link ArrayOfPermissionType }
     * 
     */
    public ArrayOfPermissionType createArrayOfPermissionType() {
        return new ArrayOfPermissionType();
    }

    /**
     * Create an instance of {@link TransRetailInfoType }
     * 
     */
    public TransRetailInfoType createTransRetailInfoType() {
        return new TransRetailInfoType();
    }

    /**
     * Create an instance of {@link GetHostedProfilePageRequest }
     * 
     */
    public GetHostedProfilePageRequest createGetHostedProfilePageRequest() {
        return new GetHostedProfilePageRequest();
    }

    /**
     * Create an instance of {@link ArrayOfSetting }
     * 
     */
    public ArrayOfSetting createArrayOfSetting() {
        return new ArrayOfSetting();
    }

    /**
     * Create an instance of {@link AuthenticateTestRequest }
     * 
     */
    public AuthenticateTestRequest createAuthenticateTestRequest() {
        return new AuthenticateTestRequest();
    }

    /**
     * Create an instance of {@link CreateCustomerPaymentProfileRequest }
     * 
     */
    public CreateCustomerPaymentProfileRequest createCreateCustomerPaymentProfileRequest() {
        return new CreateCustomerPaymentProfileRequest();
    }

    /**
     * Create an instance of {@link CustomerPaymentProfileType }
     * 
     */
    public CustomerPaymentProfileType createCustomerPaymentProfileType() {
        return new CustomerPaymentProfileType();
    }

    /**
     * Create an instance of {@link GetCustomerProfileIdsResponse }
     * 
     */
    public GetCustomerProfileIdsResponse createGetCustomerProfileIdsResponse() {
        return new GetCustomerProfileIdsResponse();
    }

    /**
     * Create an instance of {@link UpdateCustomerShippingAddressResponse }
     * 
     */
    public UpdateCustomerShippingAddressResponse createUpdateCustomerShippingAddressResponse() {
        return new UpdateCustomerShippingAddressResponse();
    }

    /**
     * Create an instance of {@link ARBCreateSubscriptionRequest }
     * 
     */
    public ARBCreateSubscriptionRequest createARBCreateSubscriptionRequest() {
        return new ARBCreateSubscriptionRequest();
    }

    /**
     * Create an instance of {@link SendCustomerTransactionReceiptResponse }
     * 
     */
    public SendCustomerTransactionReceiptResponse createSendCustomerTransactionReceiptResponse() {
        return new SendCustomerTransactionReceiptResponse();
    }

    /**
     * Create an instance of {@link GetHostedProfilePageResponse }
     * 
     */
    public GetHostedProfilePageResponse createGetHostedProfilePageResponse() {
        return new GetHostedProfilePageResponse();
    }

    /**
     * Create an instance of {@link GetTransactionListResponse }
     * 
     */
    public GetTransactionListResponse createGetTransactionListResponse() {
        return new GetTransactionListResponse();
    }

    /**
     * Create an instance of {@link ArrayOfTransactionSummaryType }
     * 
     */
    public ArrayOfTransactionSummaryType createArrayOfTransactionSummaryType() {
        return new ArrayOfTransactionSummaryType();
    }

    /**
     * Create an instance of {@link GetBatchStatisticsRequest }
     * 
     */
    public GetBatchStatisticsRequest createGetBatchStatisticsRequest() {
        return new GetBatchStatisticsRequest();
    }

    /**
     * Create an instance of {@link GetUnsettledTransactionListResponse }
     * 
     */
    public GetUnsettledTransactionListResponse createGetUnsettledTransactionListResponse() {
        return new GetUnsettledTransactionListResponse();
    }

    /**
     * Create an instance of {@link ValidateCustomerPaymentProfileResponse }
     * 
     */
    public ValidateCustomerPaymentProfileResponse createValidateCustomerPaymentProfileResponse() {
        return new ValidateCustomerPaymentProfileResponse();
    }

    /**
     * Create an instance of {@link UpdateCustomerPaymentProfileRequest }
     * 
     */
    public UpdateCustomerPaymentProfileRequest createUpdateCustomerPaymentProfileRequest() {
        return new UpdateCustomerPaymentProfileRequest();
    }

    /**
     * Create an instance of {@link CustomerPaymentProfileExType }
     * 
     */
    public CustomerPaymentProfileExType createCustomerPaymentProfileExType() {
        return new CustomerPaymentProfileExType();
    }

    /**
     * Create an instance of {@link MobileDeviceRegistrationRequest }
     * 
     */
    public MobileDeviceRegistrationRequest createMobileDeviceRegistrationRequest() {
        return new MobileDeviceRegistrationRequest();
    }

    /**
     * Create an instance of {@link MobileDeviceType }
     * 
     */
    public MobileDeviceType createMobileDeviceType() {
        return new MobileDeviceType();
    }

    /**
     * Create an instance of {@link GetTransactionListRequest }
     * 
     */
    public GetTransactionListRequest createGetTransactionListRequest() {
        return new GetTransactionListRequest();
    }

    /**
     * Create an instance of {@link OrderType }
     * 
     */
    public OrderType createOrderType() {
        return new OrderType();
    }

    /**
     * Create an instance of {@link CustomerDataType }
     * 
     */
    public CustomerDataType createCustomerDataType() {
        return new CustomerDataType();
    }

    /**
     * Create an instance of {@link OrderExType }
     * 
     */
    public OrderExType createOrderExType() {
        return new OrderExType();
    }

    /**
     * Create an instance of {@link CreditCardTrackType }
     * 
     */
    public CreditCardTrackType createCreditCardTrackType() {
        return new CreditCardTrackType();
    }

    /**
     * Create an instance of {@link SettingType }
     * 
     */
    public SettingType createSettingType() {
        return new SettingType();
    }

    /**
     * Create an instance of {@link EncryptedTrackDataType }
     * 
     */
    public EncryptedTrackDataType createEncryptedTrackDataType() {
        return new EncryptedTrackDataType();
    }

    /**
     * Create an instance of {@link SubscriptionPaymentType }
     * 
     */
    public SubscriptionPaymentType createSubscriptionPaymentType() {
        return new SubscriptionPaymentType();
    }

    /**
     * Create an instance of {@link TransactionSummaryType }
     * 
     */
    public TransactionSummaryType createTransactionSummaryType() {
        return new TransactionSummaryType();
    }

    /**
     * Create an instance of {@link ProfileTransAuthCaptureType }
     * 
     */
    public ProfileTransAuthCaptureType createProfileTransAuthCaptureType() {
        return new ProfileTransAuthCaptureType();
    }

    /**
     * Create an instance of {@link UserField }
     * 
     */
    public UserField createUserField() {
        return new UserField();
    }

    /**
     * Create an instance of {@link KeyValue }
     * 
     */
    public KeyValue createKeyValue() {
        return new KeyValue();
    }

    /**
     * Create an instance of {@link PaymentType }
     * 
     */
    public PaymentType createPaymentType() {
        return new PaymentType();
    }

    /**
     * Create an instance of {@link ProfileTransAuthOnlyType }
     * 
     */
    public ProfileTransAuthOnlyType createProfileTransAuthOnlyType() {
        return new ProfileTransAuthOnlyType();
    }

    /**
     * Create an instance of {@link ProfileTransVoidType }
     * 
     */
    public ProfileTransVoidType createProfileTransVoidType() {
        return new ProfileTransVoidType();
    }

    /**
     * Create an instance of {@link LineItemType }
     * 
     */
    public LineItemType createLineItemType() {
        return new LineItemType();
    }

    /**
     * Create an instance of {@link ProfileTransCaptureOnlyType }
     * 
     */
    public ProfileTransCaptureOnlyType createProfileTransCaptureOnlyType() {
        return new ProfileTransCaptureOnlyType();
    }

    /**
     * Create an instance of {@link ExtendedAmountType }
     * 
     */
    public ExtendedAmountType createExtendedAmountType() {
        return new ExtendedAmountType();
    }

    /**
     * Create an instance of {@link PaymentSimpleType }
     * 
     */
    public PaymentSimpleType createPaymentSimpleType() {
        return new PaymentSimpleType();
    }

    /**
     * Create an instance of {@link NameAndAddressType }
     * 
     */
    public NameAndAddressType createNameAndAddressType() {
        return new NameAndAddressType();
    }

    /**
     * Create an instance of {@link FDSFilterType }
     * 
     */
    public FDSFilterType createFDSFilterType() {
        return new FDSFilterType();
    }

    /**
     * Create an instance of {@link BankAccountMaskedType }
     * 
     */
    public BankAccountMaskedType createBankAccountMaskedType() {
        return new BankAccountMaskedType();
    }

    /**
     * Create an instance of {@link ProfileTransOrderType }
     * 
     */
    public ProfileTransOrderType createProfileTransOrderType() {
        return new ProfileTransOrderType();
    }

    /**
     * Create an instance of {@link ArrayOfLong }
     * 
     */
    public ArrayOfLong createArrayOfLong() {
        return new ArrayOfLong();
    }

    /**
     * Create an instance of {@link ProfileTransPriorAuthCaptureType }
     * 
     */
    public ProfileTransPriorAuthCaptureType createProfileTransPriorAuthCaptureType() {
        return new ProfileTransPriorAuthCaptureType();
    }

    /**
     * Create an instance of {@link ProfileTransAmountType }
     * 
     */
    public ProfileTransAmountType createProfileTransAmountType() {
        return new ProfileTransAmountType();
    }

    /**
     * Create an instance of {@link CreditCardType }
     * 
     */
    public CreditCardType createCreditCardType() {
        return new CreditCardType();
    }

    /**
     * Create an instance of {@link CustomerType }
     * 
     */
    public CustomerType createCustomerType() {
        return new CustomerType();
    }

    /**
     * Create an instance of {@link KeyBlock }
     * 
     */
    public KeyBlock createKeyBlock() {
        return new KeyBlock();
    }

    /**
     * Create an instance of {@link DriversLicenseType }
     * 
     */
    public DriversLicenseType createDriversLicenseType() {
        return new DriversLicenseType();
    }

    /**
     * Create an instance of {@link CreditCardSimpleType }
     * 
     */
    public CreditCardSimpleType createCreditCardSimpleType() {
        return new CreditCardSimpleType();
    }

    /**
     * Create an instance of {@link ArrayOfFDSFilter }
     * 
     */
    public ArrayOfFDSFilter createArrayOfFDSFilter() {
        return new ArrayOfFDSFilter();
    }

    /**
     * Create an instance of {@link BankAccountType }
     * 
     */
    public BankAccountType createBankAccountType() {
        return new BankAccountType();
    }

    /**
     * Create an instance of {@link CcAuthenticationType }
     * 
     */
    public CcAuthenticationType createCcAuthenticationType() {
        return new CcAuthenticationType();
    }

    /**
     * Create an instance of {@link ArrayOfBatchStatisticType }
     * 
     */
    public ArrayOfBatchStatisticType createArrayOfBatchStatisticType() {
        return new ArrayOfBatchStatisticType();
    }

    /**
     * Create an instance of {@link ProfileTransRefundType }
     * 
     */
    public ProfileTransRefundType createProfileTransRefundType() {
        return new ProfileTransRefundType();
    }

    /**
     * Create an instance of {@link PayPalType }
     * 
     */
    public PayPalType createPayPalType() {
        return new PayPalType();
    }

    /**
     * Create an instance of {@link ImpersonationAuthenticationType }
     * 
     */
    public ImpersonationAuthenticationType createImpersonationAuthenticationType() {
        return new ImpersonationAuthenticationType();
    }

    /**
     * Create an instance of {@link PaymentMaskedType }
     * 
     */
    public PaymentMaskedType createPaymentMaskedType() {
        return new PaymentMaskedType();
    }

    /**
     * Create an instance of {@link CustomerPaymentProfileBaseType }
     * 
     */
    public CustomerPaymentProfileBaseType createCustomerPaymentProfileBaseType() {
        return new CustomerPaymentProfileBaseType();
    }

    /**
     * Create an instance of {@link CreditCardMaskedType }
     * 
     */
    public CreditCardMaskedType createCreditCardMaskedType() {
        return new CreditCardMaskedType();
    }

    /**
     * Create an instance of {@link DriversLicenseMaskedType }
     * 
     */
    public DriversLicenseMaskedType createDriversLicenseMaskedType() {
        return new DriversLicenseMaskedType();
    }

    /**
     * Create an instance of {@link ArrayOfLineItem }
     * 
     */
    public ArrayOfLineItem createArrayOfLineItem() {
        return new ArrayOfLineItem();
    }

    /**
     * Create an instance of {@link PermissionType }
     * 
     */
    public PermissionType createPermissionType() {
        return new PermissionType();
    }

    /**
     * Create an instance of {@link BatchStatisticType }
     * 
     */
    public BatchStatisticType createBatchStatisticType() {
        return new BatchStatisticType();
    }

    /**
     * Create an instance of {@link CustomerProfileBaseType }
     * 
     */
    public CustomerProfileBaseType createCustomerProfileBaseType() {
        return new CustomerProfileBaseType();
    }

    /**
     * Create an instance of {@link KeyManagementScheme.DUKPT.Mode }
     * 
     */
    public KeyManagementScheme.DUKPT.Mode createKeyManagementSchemeDUKPTMode() {
        return new KeyManagementScheme.DUKPT.Mode();
    }

    /**
     * Create an instance of {@link KeyManagementScheme.DUKPT.DeviceInfo }
     * 
     */
    public KeyManagementScheme.DUKPT.DeviceInfo createKeyManagementSchemeDUKPTDeviceInfo() {
        return new KeyManagementScheme.DUKPT.DeviceInfo();
    }

    /**
     * Create an instance of {@link KeyManagementScheme.DUKPT.EncryptedData }
     * 
     */
    public KeyManagementScheme.DUKPT.EncryptedData createKeyManagementSchemeDUKPTEncryptedData() {
        return new KeyManagementScheme.DUKPT.EncryptedData();
    }

    /**
     * Create an instance of {@link PaymentScheduleType.Interval }
     * 
     */
    public PaymentScheduleType.Interval createPaymentScheduleTypeInterval() {
        return new PaymentScheduleType.Interval();
    }

    /**
     * Create an instance of {@link TransactionRequestType.UserFields }
     * 
     */
    public TransactionRequestType.UserFields createTransactionRequestTypeUserFields() {
        return new TransactionRequestType.UserFields();
    }

    /**
     * Create an instance of {@link TransactionResponse.PrePaidCard }
     * 
     */
    public TransactionResponse.PrePaidCard createTransactionResponsePrePaidCard() {
        return new TransactionResponse.PrePaidCard();
    }

    /**
     * Create an instance of {@link TransactionResponse.UserFields }
     * 
     */
    public TransactionResponse.UserFields createTransactionResponseUserFields() {
        return new TransactionResponse.UserFields();
    }

    /**
     * Create an instance of {@link TransactionResponse.SecureAcceptance }
     * 
     */
    public TransactionResponse.SecureAcceptance createTransactionResponseSecureAcceptance() {
        return new TransactionResponse.SecureAcceptance();
    }

    /**
     * Create an instance of {@link TransactionResponse.SplitTenderPayments.SplitTenderPayment }
     * 
     */
    public TransactionResponse.SplitTenderPayments.SplitTenderPayment createTransactionResponseSplitTenderPaymentsSplitTenderPayment() {
        return new TransactionResponse.SplitTenderPayments.SplitTenderPayment();
    }

    /**
     * Create an instance of {@link TransactionResponse.Errors.Error }
     * 
     */
    public TransactionResponse.Errors.Error createTransactionResponseErrorsError() {
        return new TransactionResponse.Errors.Error();
    }

    /**
     * Create an instance of {@link TransactionResponse.Messages.Message }
     * 
     */
    public TransactionResponse.Messages.Message createTransactionResponseMessagesMessage() {
        return new TransactionResponse.Messages.Message();
    }

    /**
     * Create an instance of {@link MessagesType.Message }
     * 
     */
    public MessagesType.Message createMessagesTypeMessage() {
        return new MessagesType.Message();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ANetApiResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "ErrorResponse")
    public JAXBElement<ANetApiResponse> createErrorResponse(ANetApiResponse value) {
        return new JAXBElement<ANetApiResponse>(_ErrorResponse_QNAME, ANetApiResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderExType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "order", scope = TransactionDetailsType.class)
    public JAXBElement<OrderExType> createTransactionDetailsTypeOrder(OrderExType value) {
        return new JAXBElement<OrderExType>(_TransactionDetailsTypeOrder_QNAME, OrderExType.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "refTransId", scope = TransactionDetailsType.class)
    public JAXBElement<String> createTransactionDetailsTypeRefTransId(String value) {
        return new JAXBElement<String>(_TransactionDetailsTypeRefTransId_QNAME, String.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PaymentMaskedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "payment", scope = TransactionDetailsType.class)
    public JAXBElement<PaymentMaskedType> createTransactionDetailsTypePayment(PaymentMaskedType value) {
        return new JAXBElement<PaymentMaskedType>(_TransactionDetailsTypePayment_QNAME, PaymentMaskedType.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "cardCodeResponse", scope = TransactionDetailsType.class)
    public JAXBElement<String> createTransactionDetailsTypeCardCodeResponse(String value) {
        return new JAXBElement<String>(_TransactionDetailsTypeCardCodeResponse_QNAME, String.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "billTo", scope = TransactionDetailsType.class)
    public JAXBElement<CustomerAddressType> createTransactionDetailsTypeBillTo(CustomerAddressType value) {
        return new JAXBElement<CustomerAddressType>(_TransactionDetailsTypeBillTo_QNAME, CustomerAddressType.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtendedAmountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "shipping", scope = TransactionDetailsType.class)
    public JAXBElement<ExtendedAmountType> createTransactionDetailsTypeShipping(ExtendedAmountType value) {
        return new JAXBElement<ExtendedAmountType>(_TransactionDetailsTypeShipping_QNAME, ExtendedAmountType.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "mobileDeviceId", scope = TransactionDetailsType.class)
    public JAXBElement<String> createTransactionDetailsTypeMobileDeviceId(String value) {
        return new JAXBElement<String>(_TransactionDetailsTypeMobileDeviceId_QNAME, String.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfLineItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "lineItems", scope = TransactionDetailsType.class)
    public JAXBElement<ArrayOfLineItem> createTransactionDetailsTypeLineItems(ArrayOfLineItem value) {
        return new JAXBElement<ArrayOfLineItem>(_TransactionDetailsTypeLineItems_QNAME, ArrayOfLineItem.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "responseCode", scope = TransactionDetailsType.class)
    public JAXBElement<Integer> createTransactionDetailsTypeResponseCode(Integer value) {
        return new JAXBElement<Integer>(_TransactionDetailsTypeResponseCode_QNAME, Integer.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "marketType", scope = TransactionDetailsType.class)
    public JAXBElement<String> createTransactionDetailsTypeMarketType(String value) {
        return new JAXBElement<String>(_TransactionDetailsTypeMarketType_QNAME, String.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubscriptionPaymentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "subscription", scope = TransactionDetailsType.class)
    public JAXBElement<SubscriptionPaymentType> createTransactionDetailsTypeSubscription(SubscriptionPaymentType value) {
        return new JAXBElement<SubscriptionPaymentType>(_TransactionDetailsTypeSubscription_QNAME, SubscriptionPaymentType.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "responseReasonDescription", scope = TransactionDetailsType.class)
    public JAXBElement<String> createTransactionDetailsTypeResponseReasonDescription(String value) {
        return new JAXBElement<String>(_TransactionDetailsTypeResponseReasonDescription_QNAME, String.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "submitTimeLocal", scope = TransactionDetailsType.class)
    public JAXBElement<XMLGregorianCalendar> createTransactionDetailsTypeSubmitTimeLocal(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TransactionDetailsTypeSubmitTimeLocal_QNAME, XMLGregorianCalendar.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "settleAmount", scope = TransactionDetailsType.class)
    public JAXBElement<BigDecimal> createTransactionDetailsTypeSettleAmount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TransactionDetailsTypeSettleAmount_QNAME, BigDecimal.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "transId", scope = TransactionDetailsType.class)
    public JAXBElement<String> createTransactionDetailsTypeTransId(String value) {
        return new JAXBElement<String>(_TransactionDetailsTypeTransId_QNAME, String.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "splitTenderId", scope = TransactionDetailsType.class)
    public JAXBElement<String> createTransactionDetailsTypeSplitTenderId(String value) {
        return new JAXBElement<String>(_TransactionDetailsTypeSplitTenderId_QNAME, String.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "customerIP", scope = TransactionDetailsType.class)
    public JAXBElement<String> createTransactionDetailsTypeCustomerIP(String value) {
        return new JAXBElement<String>(_TransactionDetailsTypeCustomerIP_QNAME, String.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "submitTimeUTC", scope = TransactionDetailsType.class)
    public JAXBElement<XMLGregorianCalendar> createTransactionDetailsTypeSubmitTimeUTC(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TransactionDetailsTypeSubmitTimeUTC_QNAME, XMLGregorianCalendar.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomerDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "customer", scope = TransactionDetailsType.class)
    public JAXBElement<CustomerDataType> createTransactionDetailsTypeCustomer(CustomerDataType value) {
        return new JAXBElement<CustomerDataType>(_TransactionDetailsTypeCustomer_QNAME, CustomerDataType.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameAndAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "shipTo", scope = TransactionDetailsType.class)
    public JAXBElement<NameAndAddressType> createTransactionDetailsTypeShipTo(NameAndAddressType value) {
        return new JAXBElement<NameAndAddressType>(_TransactionDetailsTypeShipTo_QNAME, NameAndAddressType.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "requestedAmount", scope = TransactionDetailsType.class)
    public JAXBElement<BigDecimal> createTransactionDetailsTypeRequestedAmount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TransactionDetailsTypeRequestedAmount_QNAME, BigDecimal.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtendedAmountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "duty", scope = TransactionDetailsType.class)
    public JAXBElement<ExtendedAmountType> createTransactionDetailsTypeDuty(ExtendedAmountType value) {
        return new JAXBElement<ExtendedAmountType>(_TransactionDetailsTypeDuty_QNAME, ExtendedAmountType.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "CAVVResponse", scope = TransactionDetailsType.class)
    public JAXBElement<String> createTransactionDetailsTypeCAVVResponse(String value) {
        return new JAXBElement<String>(_TransactionDetailsTypeCAVVResponse_QNAME, String.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "recurringBilling", scope = TransactionDetailsType.class)
    public JAXBElement<Boolean> createTransactionDetailsTypeRecurringBilling(Boolean value) {
        return new JAXBElement<Boolean>(_TransactionDetailsTypeRecurringBilling_QNAME, Boolean.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "transactionType", scope = TransactionDetailsType.class)
    public JAXBElement<String> createTransactionDetailsTypeTransactionType(String value) {
        return new JAXBElement<String>(_TransactionDetailsTypeTransactionType_QNAME, String.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "FDSFilterAction", scope = TransactionDetailsType.class)
    public JAXBElement<String> createTransactionDetailsTypeFDSFilterAction(String value) {
        return new JAXBElement<String>(_TransactionDetailsTypeFDSFilterAction_QNAME, String.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "responseReasonCode", scope = TransactionDetailsType.class)
    public JAXBElement<Integer> createTransactionDetailsTypeResponseReasonCode(Integer value) {
        return new JAXBElement<Integer>(_TransactionDetailsTypeResponseReasonCode_QNAME, Integer.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "prepaidBalanceRemaining", scope = TransactionDetailsType.class)
    public JAXBElement<BigDecimal> createTransactionDetailsTypePrepaidBalanceRemaining(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TransactionDetailsTypePrepaidBalanceRemaining_QNAME, BigDecimal.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfFDSFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "FDSFilters", scope = TransactionDetailsType.class)
    public JAXBElement<ArrayOfFDSFilter> createTransactionDetailsTypeFDSFilters(ArrayOfFDSFilter value) {
        return new JAXBElement<ArrayOfFDSFilter>(_TransactionDetailsTypeFDSFilters_QNAME, ArrayOfFDSFilter.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "authAmount", scope = TransactionDetailsType.class)
    public JAXBElement<BigDecimal> createTransactionDetailsTypeAuthAmount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TransactionDetailsTypeAuthAmount_QNAME, BigDecimal.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtendedAmountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "tax", scope = TransactionDetailsType.class)
    public JAXBElement<ExtendedAmountType> createTransactionDetailsTypeTax(ExtendedAmountType value) {
        return new JAXBElement<ExtendedAmountType>(_TransactionDetailsTypeTax_QNAME, ExtendedAmountType.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BatchDetailsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "batch", scope = TransactionDetailsType.class)
    public JAXBElement<BatchDetailsType> createTransactionDetailsTypeBatch(BatchDetailsType value) {
        return new JAXBElement<BatchDetailsType>(_TransactionDetailsTypeBatch_QNAME, BatchDetailsType.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "transactionStatus", scope = TransactionDetailsType.class)
    public JAXBElement<String> createTransactionDetailsTypeTransactionStatus(String value) {
        return new JAXBElement<String>(_TransactionDetailsTypeTransactionStatus_QNAME, String.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "authCode", scope = TransactionDetailsType.class)
    public JAXBElement<String> createTransactionDetailsTypeAuthCode(String value) {
        return new JAXBElement<String>(_TransactionDetailsTypeAuthCode_QNAME, String.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "taxExempt", scope = TransactionDetailsType.class)
    public JAXBElement<Boolean> createTransactionDetailsTypeTaxExempt(Boolean value) {
        return new JAXBElement<Boolean>(_TransactionDetailsTypeTaxExempt_QNAME, Boolean.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "product", scope = TransactionDetailsType.class)
    public JAXBElement<String> createTransactionDetailsTypeProduct(String value) {
        return new JAXBElement<String>(_TransactionDetailsTypeProduct_QNAME, String.class, TransactionDetailsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", name = "AVSResponse", scope = TransactionDetailsType.class)
    public JAXBElement<String> createTransactionDetailsTypeAVSResponse(String value) {
        return new JAXBElement<String>(_TransactionDetailsTypeAVSResponse_QNAME, String.class, TransactionDetailsType.class, value);
    }

}
