/*
 * Authorize.Net REST API
 *
 * Authorize.Net REST API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Contains the information to create a profile and an associated payment method.
    /// </summary>
    [DataContract]
    public partial class CreateCustomerAndPaymentMethod : IEquatable<CreateCustomerAndPaymentMethod>
    { 
        /// <summary>
        /// Description of the customer or customer profile. Required only when no values for &#x60;merchantCustomerId&#x60; and &#x60;email&#x60; are submitted. 255-character maximum.
        /// </summary>
        /// <value>Description of the customer or customer profile. Required only when no values for &#x60;merchantCustomerId&#x60; and &#x60;email&#x60; are submitted. 255-character maximum.</value>

        [DataMember(Name="description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Identifier
        /// </summary>
        [Required]

        [DataMember(Name="identifier")]
        public Identifier Identifier { get; set; }

        /// <summary>
        /// Gets or Sets PaymentMethod
        /// </summary>

        [DataMember(Name="paymentMethod")]
        public CreatePaymentMethod PaymentMethod { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateCustomerAndPaymentMethod {\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Identifier: ").Append(Identifier).Append("\n");
            sb.Append("  PaymentMethod: ").Append(PaymentMethod).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreateCustomerAndPaymentMethod)obj);
        }

        /// <summary>
        /// Returns true if CreateCustomerAndPaymentMethod instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateCustomerAndPaymentMethod to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateCustomerAndPaymentMethod other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) && 
                (
                    Identifier == other.Identifier ||
                    Identifier != null &&
                    Identifier.Equals(other.Identifier)
                ) && 
                (
                    PaymentMethod == other.PaymentMethod ||
                    PaymentMethod != null &&
                    PaymentMethod.Equals(other.PaymentMethod)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                    if (Identifier != null)
                    hashCode = hashCode * 59 + Identifier.GetHashCode();
                    if (PaymentMethod != null)
                    hashCode = hashCode * 59 + PaymentMethod.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreateCustomerAndPaymentMethod left, CreateCustomerAndPaymentMethod right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreateCustomerAndPaymentMethod left, CreateCustomerAndPaymentMethod right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
