/*
 * Authorize.Net REST API
 *
 * Authorize.Net REST API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Contains information about a customer&#x27;s payment method.
    /// </summary>
    [DataContract]
    public partial class CreatePaymentMethod : IEquatable<CreatePaymentMethod>
    { 
        /// <summary>
        /// Unique identifier of the address associated with the payment method.
        /// </summary>
        /// <value>Unique identifier of the address associated with the payment method.</value>

        [DataMember(Name="addressId")]
        public string AddressId { get; set; }

        /// <summary>
        /// Gets or Sets BillTo
        /// </summary>

        [DataMember(Name="billTo")]
        public BaseAddress BillTo { get; set; }

        /// <summary>
        /// Setting this to &#x60;true&#x60; sets this payment method as the default for this customer profile.
        /// </summary>
        /// <value>Setting this to &#x60;true&#x60; sets this payment method as the default for this customer profile.</value>

        [DataMember(Name="default")]
        public bool? _Default { get; set; }

        /// <summary>
        /// Gets or Sets PaymentInformation
        /// </summary>

        [DataMember(Name="paymentInformation")]
        public PaymentInformation PaymentInformation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreatePaymentMethod {\n");
            sb.Append("  AddressId: ").Append(AddressId).Append("\n");
            sb.Append("  BillTo: ").Append(BillTo).Append("\n");
            sb.Append("  _Default: ").Append(_Default).Append("\n");
            sb.Append("  PaymentInformation: ").Append(PaymentInformation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreatePaymentMethod)obj);
        }

        /// <summary>
        /// Returns true if CreatePaymentMethod instances are equal
        /// </summary>
        /// <param name="other">Instance of CreatePaymentMethod to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreatePaymentMethod other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    AddressId == other.AddressId ||
                    AddressId != null &&
                    AddressId.Equals(other.AddressId)
                ) && 
                (
                    BillTo == other.BillTo ||
                    BillTo != null &&
                    BillTo.Equals(other.BillTo)
                ) && 
                (
                    _Default == other._Default ||
                    _Default != null &&
                    _Default.Equals(other._Default)
                ) && 
                (
                    PaymentInformation == other.PaymentInformation ||
                    PaymentInformation != null &&
                    PaymentInformation.Equals(other.PaymentInformation)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (AddressId != null)
                    hashCode = hashCode * 59 + AddressId.GetHashCode();
                    if (BillTo != null)
                    hashCode = hashCode * 59 + BillTo.GetHashCode();
                    if (_Default != null)
                    hashCode = hashCode * 59 + _Default.GetHashCode();
                    if (PaymentInformation != null)
                    hashCode = hashCode * 59 + PaymentInformation.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreatePaymentMethod left, CreatePaymentMethod right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreatePaymentMethod left, CreatePaymentMethod right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
