//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.25 at 03:55:04 PM IST 
//


package net.authorize.api.contract.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for auDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="auDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="customerProfileID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="customerPaymentProfileID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="updateTimeUTC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="auReasonCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reasonDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "auDetailsType", propOrder = {
    "customerProfileID",
    "customerPaymentProfileID",
    "firstName",
    "lastName",
    "updateTimeUTC",
    "auReasonCode",
    "reasonDescription"
})
@XmlSeeAlso({
    AuDeleteType.class,
    AuUpdateType.class
})
public class AuDetailsType {

    protected long customerProfileID;
    protected long customerPaymentProfileID;
    protected String firstName;
    protected String lastName;
    @XmlElement(required = true)
    protected String updateTimeUTC;
    @XmlElement(required = true)
    protected String auReasonCode;
    @XmlElement(required = true)
    protected String reasonDescription;

    /**
     * Gets the value of the customerProfileID property.
     * 
     */
    public long getCustomerProfileID() {
        return customerProfileID;
    }

    /**
     * Sets the value of the customerProfileID property.
     * 
     */
    public void setCustomerProfileID(long value) {
        this.customerProfileID = value;
    }

    /**
     * Gets the value of the customerPaymentProfileID property.
     * 
     */
    public long getCustomerPaymentProfileID() {
        return customerPaymentProfileID;
    }

    /**
     * Sets the value of the customerPaymentProfileID property.
     * 
     */
    public void setCustomerPaymentProfileID(long value) {
        this.customerPaymentProfileID = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the updateTimeUTC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateTimeUTC() {
        return updateTimeUTC;
    }

    /**
     * Sets the value of the updateTimeUTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateTimeUTC(String value) {
        this.updateTimeUTC = value;
    }

    /**
     * Gets the value of the auReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuReasonCode() {
        return auReasonCode;
    }

    /**
     * Sets the value of the auReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuReasonCode(String value) {
        this.auReasonCode = value;
    }

    /**
     * Gets the value of the reasonDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonDescription() {
        return reasonDescription;
    }

    /**
     * Sets the value of the reasonDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonDescription(String value) {
        this.reasonDescription = value;
    }

}
