//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.25 at 03:55:04 PM IST 
//


package net.authorize.api.contract.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{AnetApi/xml/v1/schema/AnetApiSchema.xsd}ANetApiResponse">
 *       &lt;sequence>
 *         &lt;element name="merchantContact" type="{AnetApi/xml/v1/schema/AnetApiSchema.xsd}merchantContactType"/>
 *         &lt;element name="userPermissions" type="{AnetApi/xml/v1/schema/AnetApiSchema.xsd}ArrayOfPermissionType"/>
 *         &lt;element name="merchantAccount" type="{AnetApi/xml/v1/schema/AnetApiSchema.xsd}transRetailInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "merchantContact",
    "userPermissions",
    "merchantAccount"
})
@XmlRootElement(name = "mobileDeviceLoginResponse")
public class MobileDeviceLoginResponse
    extends ANetApiResponse
{

    @XmlElement(required = true)
    protected MerchantContactType merchantContact;
    @XmlElement(required = true)
    protected ArrayOfPermissionType userPermissions;
    protected TransRetailInfoType merchantAccount;

    /**
     * Gets the value of the merchantContact property.
     * 
     * @return
     *     possible object is
     *     {@link MerchantContactType }
     *     
     */
    public MerchantContactType getMerchantContact() {
        return merchantContact;
    }

    /**
     * Sets the value of the merchantContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchantContactType }
     *     
     */
    public void setMerchantContact(MerchantContactType value) {
        this.merchantContact = value;
    }

    /**
     * Gets the value of the userPermissions property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfPermissionType }
     *     
     */
    public ArrayOfPermissionType getUserPermissions() {
        return userPermissions;
    }

    /**
     * Sets the value of the userPermissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfPermissionType }
     *     
     */
    public void setUserPermissions(ArrayOfPermissionType value) {
        this.userPermissions = value;
    }

    /**
     * Gets the value of the merchantAccount property.
     * 
     * @return
     *     possible object is
     *     {@link TransRetailInfoType }
     *     
     */
    public TransRetailInfoType getMerchantAccount() {
        return merchantAccount;
    }

    /**
     * Sets the value of the merchantAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransRetailInfoType }
     *     
     */
    public void setMerchantAccount(TransRetailInfoType value) {
        this.merchantAccount = value;
    }

}
