//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.14 at 11:09:15 AM IST 
//


package net.authorize.api.contract.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for subsequentAuthInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="subsequentAuthInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="originalNetworkTransId" type="{AnetApi/xml/v1/schema/AnetApiSchema.xsd}networkTransId" minOccurs="0"/>
 *         &lt;element name="reason" type="{AnetApi/xml/v1/schema/AnetApiSchema.xsd}merchantInitTransReasonEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "subsequentAuthInformation", propOrder = {
    "originalNetworkTransId",
    "reason"
})
public class SubsequentAuthInformation {

    protected String originalNetworkTransId;
    @XmlSchemaType(name = "string")
    protected MerchantInitTransReasonEnum reason;

    /**
     * Gets the value of the originalNetworkTransId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalNetworkTransId() {
        return originalNetworkTransId;
    }

    /**
     * Sets the value of the originalNetworkTransId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalNetworkTransId(String value) {
        this.originalNetworkTransId = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link MerchantInitTransReasonEnum }
     *     
     */
    public MerchantInitTransReasonEnum getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchantInitTransReasonEnum }
     *     
     */
    public void setReason(MerchantInitTransReasonEnum value) {
        this.reason = value;
    }

}
